standard = "2019"
[lint]
unused = false
# superfluous_in_sensitivity_list = false  # ? LSP supports it, extension doesn't
[libraries]
common_lib.files = []
common_lib.is_third_party = true
unisim.files = ['C:/Xilinx/Vivado/2024.2/data/vhdl/src/unisims/unisim_VCOMP.vhd']
axis_avg_buffer.files = ["firmware/ip/axis_avg_buffer/src/**/*.vhd"]
axis_buffer_ddr_v1.files = ["firmware/ip/axis_buffer_ddr_v1/src/**/*.vhd"]
axis_cdcsync_v1.files = ["firmware/ip/axis_cdcsync_v1/src/**/*.vhd"]
axis_constant.files = ["firmware/ip/axis_constant/src/**/*.vhd"]
axis_constant_iq.files = ["firmware/ip/axis_constant_iq/src/**/*.vhd"]
axis_dyn_readout_v1.files = ["firmware/ip/axis_dyn_readout_v1/src/**/*.vhd"]
axis_kidsim_v3.files = ["firmware/ip/axis_kidsim_v3/src/**/*.vhd"]
axis_readout_v1.files = ["firmware/ip/axis_readout_v1/src/**/*.vhd"]
axis_readout_v2.files = ["firmware/ip/axis_readout_v2/src/**/*.vhd"]
axis_readout_v3.files = ["firmware/ip/axis_readout_v3/src/**/*.vhd"]
axis_register_slice_nb.files = ["firmware/ip/axis_register_slice_nb/src/**/*.vhd"]
axis_set_reg.files = ["firmware/ip/axis_set_reg/src/**/*.vhd"]
axis_sg_int4_v1.files = ["firmware/ip/axis_sg_int4_v1/src/**/*.vhd"]
axis_sg_int4_v2.files = ["firmware/ip/axis_sg_int4_v2/src/**/*.vhd"]
axis_sg_mixmux8_v1.files = ["firmware/ip/axis_sg_mixmux8_v1/src/**/*.vhd"]
axis_sg_mux4_v1.files = ["firmware/ip/axis_sg_mux4_v1/src/**/*.vhd"]
axis_sg_mux4_v2.files = ["firmware/ip/axis_sg_mux4_v2/src/**/*.vhd"]
axis_sg_mux4_v3.files = ["firmware/ip/axis_sg_mux4_v3/src/**/*.vhd"]
axis_sg_mux8_v1.files = ["firmware/ip/axis_sg_mux8_v1/src/**/*.vhd"]
axis_signal_gen_v4.files = ["firmware/ip/axis_signal_gen_v4/src/**/*.vhd"]
axis_signal_gen_v5.files = ["firmware/ip/axis_signal_gen_v5/src/**/*.vhd"]
axis_signal_gen_v6.files = ["firmware/ip/axis_signal_gen_v6/src/**/*.vhd"]
axis_terminator.files = ["firmware/ip/axis_terminator/src/**/*.vhd"]
axis_tproc64x32_x8_v1.files = ["firmware/ip/axis_tproc64x32_x8_v1/src/**/*.vhd"]
mr_buffer_et.files = ["firmware/ip/mr_buffer_et/src/**/*.vhd"]
qick_com.files = ["firmware/ip/qick_com/src/**/*.vhd"]
qick_peripheral_template.files = ["firmware/ip/qick_peripheral_template/src/**/*.vhd"]
qick_processor.files = ["firmware/ip/qick_processor/src/**/*.vhd"]
qick_time_tagger.files = ["firmware/ip/qick_time_tagger/src/**/*.vhd"]
